# Generated by Django 6.0.5 on 2026-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
