# Generated by Django 6.0.5 on 2026-05-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_vote_candidate_alter_vote_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user_id',
        ),
        migrations.AddField(
            model_name='vote',
            name='aadhaar_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
