# Generated by Django 6.0.5 on 2026-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_vote_id_type_remove_vote_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='aadhaar_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
