# Generated by Django 6.0.5 on 2026-05-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_vote_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
